### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Oksana8** [Oksana8/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Oksana-for-testing** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend, and an employee I am known as contemplative, tortured, and driven.

**Comment by Oksana8** [comment]
I wander the world with the desire for complete mastery of his martial art and take both my travels and training seriously.  The training and the mastery that comes from the fight are all that I require for satisfaction
