### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Oksana8** [Oksana8/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Oksana-for-testing** [comment]
https://www.facebook.com/profile.php?id=100004808958030
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
ryuwins@gmail.com

**Comment by Oksana8** [comment]
https://www.facebook.com/profile.php?id=100004808958030
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
email: ryuwins@gmail.com
